apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expensy-ingress
  namespace: ${NAMESPACE}
  annotations:
    # NGINX
    kubernetes.io/ingress.class: nginx

    # CERT MANAGER
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"

    # FORCE HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

    # REWRITE API PATH
    nginx.ingress.kubernetes.io/rewrite-target: /$2

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ${DOMAIN_NAME}
      secretName: expensy-tls
  rules:
    - host: ${DOMAIN_NAME}
      http:
        paths:
          # BACKEND API
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific

            backend:
              service:
                name: backend-service
                port:
                  number: 8706

          # FRONTEND
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 3000
