apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: expensy

data:
  PORT: "8706"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  DATABASE_URI: "mongodb://root:example@mongo-service:27017"
