name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

      image_tag:
        required: false
        type: string
        default: latest

  workflow_dispatch:
    inputs:
      environment:
        description: Select Environment
        required: true
        type: choice

        options:
          - dev
          - staging
          - production

      image_tag:
        description: Docker image tag
        required: false
        default: latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment || github.event.inputs.environment }}

    env:
      ENVIRONMENT: ${{ inputs.environment || github.event.inputs.environment }}

      NAMESPACE: ${{ vars.NAMESPACE }}
      DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}

      REDIS_IMAGE: ${{ vars.REDIS_IMAGE }}
      MONGO_IMAGE: ${{ vars.MONGO_IMAGE }}

      BACKEND_IMAGE: babanila/expensy_backend
      FRONTEND_IMAGE: babanila/expensy_frontend

      IMAGE_TAG: ${{ inputs.image_tag || github.sha }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS Context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
      
      - name: Verify Cluster
        run: |
          kubectl cluster-info
          kubectl get nodes


      - name: Create Env File
        run: |
          cat <<EOF > .env
          ENVIRONMENT=${ENVIRONMENT}
          NAMESPACE=${NAMESPACE}
          DOMAIN_NAME=${DOMAIN_NAME}
          REDIS_IMAGE=${REDIS_IMAGE}
          MONGO_IMAGE=${MONGO_IMAGE}
          BACKEND_IMAGE=${BACKEND_IMAGE}
          FRONTEND_IMAGE=${FRONTEND_IMAGE}
          IMAGE_TAG=${IMAGE_TAG}
          EOF

          echo "Generated .env file:"
          cat .env

      - name: Deploy Application
        env:
          FORCE_INGRESS_REINSTALL: "false"
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh

      - name: Verify Backend Rollout
        run: |
          kubectl rollout status deployment/backend \
            -n "${NAMESPACE}" \
            --timeout=300s

      - name: Verify Frontend Rollout
        run: |
          kubectl rollout status deployment/frontend \
            -n "${NAMESPACE}" \
            --timeout=300s

      - name: Show Resources
        run: |
          kubectl get all -n "${NAMESPACE}"
